package com.johnsamte.labupi

data class LabuData(
    val id : Int,
    val la_number : String,
    val la_thulu : String,
    val la_thupineu : String?,
    val la_phuaktu1 : String?,
    val la_phuaktu2 : String?,
    val la_phuaktu3 : String?,
    val la_phuaktu4 : String?,
    val la_key : String?,
    val la_text1 : String,
    val chorus1 : String?,
    val la_text2 : String?,
    val chorus2 : String?,
    val la_text3 : String?,
    val chorus3 : String?,
    val la_text4 : String?,
    val chorus4 : String?,
    val la_text5 : String?,
    val chorus5 : String?,
    val la_text6 : String?,
    val chorus6 : String?,
    val la_text7 : String?,
    val chorus7 : String?,
    val la_text8 : String?,
    val chorus8 : String?,
    val la_text9 : String?,
    val la_text10 : String?,
)
